spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.41.177.68:19708/ekcloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: IVhcwyTj
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 100
      use-unfair-lock: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: true
      filter: stat,slf4j
      use-global-data-source-stat: true
      pool-prepared-statements: false
  cloud:
    nacos:
      server-addr: 121.41.177.68:8848
      discovery:
        service: ${spring.application.name}
        group: ek-cloud
        namespace: ek-cloud-dev

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml #classpath*:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.ouke.cloud: debug
  file:
    path: d:/ek-logs/ek-cloud-member
