server:
  port: 10737

spring:
  application:
    name: ek-cloud-order-provider
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.126.129:8848
        service: ek-cloud-order-provider
logging:
  level:
    root: INFO
  file:
    path: d:/ek-logs/ek-cloud-member